site_name: Vector1
site_url: https://BenSBk.github.io/Vector1
repo_name: BenSBk/Vector1
repo_url: https://github.com/BenSBk/Vector1

theme:
  name: material
  palette:
    primary: "Light Blue"
    accent: "Light Blue"

nav:
  - Home: index.md
  - API: api.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
